// @ts-nocheck
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Run a resolved user command line through the platform shell and capture its output (CPE-783). The
 * frontend confirms the command with the user first — see the module comment. Async per the commands rule.
 */
async runCommand(command: string, cwd: string | null) : Promise<Result<CommandOutput, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_command", { command, cwd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new directory `name` inside `path`.
 */
async createDir(path: string, name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_dir", { path, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new empty file `name` inside `path` (CPE-254). Mirrors `create_dir`:
 * `create_new` fails atomically rather than clobbering an existing file.
 */
async createFile(path: string, name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_file", { path, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write UTF-8 text back to a file, replacing its contents — for the content
 * editor. Returns the new byte length.
 */
async writeFileText(path: string, contents: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file_text", { path, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a single entry in place. Returns the new path.
 */
async renameEntry(path: string, newName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_entry", { path, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Can this platform restore items from the OS trash?
 * 
 * `trash::os_limited` (list + restore) is implemented on Windows and Linux but
 * NOT on macOS. The UI calls this so it can decide whether to offer undo-of-
 * delete at all. Offering an Undo that silently does nothing on one platform is
 * worse than not offering it — so we tell the truth instead of guessing.
 */
async canRestoreFromTrash() : Promise<boolean> {
    return await TAURI_INVOKE("can_restore_from_trash");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Captured result of a user command run.
 */
export type CommandOutput = { stdout: string; stderr: string; 
/**
 * Process exit code, or `None` if it was terminated by a signal.
 */
code: number | null; 
/**
 * True when either stream was truncated at the cap.
 */
truncated: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "./invoke";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
