//! Baseline assertions over the pristine `samples/` fixtures (CPE-1042).
//!
//! `samples/` holds small, synthetic, KNOWN-metadata files (generated by `scripts/gen_samples.py`). This
//! test reads each one through the shipped read codecs and asserts the documented baseline — so the
//! fixtures double as a regression guard: if a codec or a sample drifts, this fails. Keep it in sync with
//! `samples/README.md`.

use cpe_server::media_meta_edit::MetaField;
use cpe_server::media_meta_read::{read_exif, read_flac, read_id3v2, read_ogg, read_pdf};
use cpe_server::video_meta_read::read_mp4;
use std::fs;
use std::path::PathBuf;

fn sample(rel: &str) -> Vec<u8> {
    let p: PathBuf = [env!("CARGO_MANIFEST_DIR"), "..", "..", "samples", rel].iter().collect();
    fs::read(&p).unwrap_or_else(|e| panic!("read sample {rel}: {e}"))
}

fn val<'a>(fields: &'a [MetaField], key: &str) -> &'a str {
    fields
        .iter()
        .find(|f| f.key == key)
        .unwrap_or_else(|| panic!("missing field {key:?} (have: {:?})", fields.iter().map(|f| &f.key).collect::<Vec<_>>()))
        .value
        .as_str()
}

#[test]
fn mp3_id3_baseline() {
    let f = read_id3v2(&sample("audio/track.mp3"));
    assert_eq!(val(&f, "Title"), "Baseline Sample");
    assert_eq!(val(&f, "Artist"), "CPE Test Suite");
    assert_eq!(val(&f, "Album"), "Known Fixtures");
    assert_eq!(val(&f, "Year"), "2026");
    assert_eq!(val(&f, "Track"), "3/10");
    assert_eq!(val(&f, "Genre"), "Ambient");
    assert!(val(&f, "Comment").starts_with("Pristine CPE sample"));
    assert!(f.iter().all(|x| x.group == "id3" && x.editable));
}

fn assert_vorbis_baseline(f: &[MetaField]) {
    assert_eq!(val(f, "Title"), "Baseline Sample");
    assert_eq!(val(f, "Artist"), "CPE Test Suite");
    assert_eq!(val(f, "Album"), "Known Fixtures");
    assert_eq!(val(f, "Year"), "2026");
    assert_eq!(val(f, "Track"), "3");
    assert_eq!(val(f, "Genre"), "Ambient");
    assert!(f.iter().all(|x| x.group == "vorbis" && x.editable));
}

#[test]
fn flac_vorbis_baseline() {
    assert_vorbis_baseline(&read_flac(&sample("audio/track.flac")));
}

#[test]
fn ogg_vorbis_baseline() {
    assert_vorbis_baseline(&read_ogg(&sample("audio/track.ogg")));
}

#[test]
fn jpeg_exif_baseline() {
    // kamadak-exif renders ASCII values with surrounding quotes, so assert on the contained text.
    let f = read_exif(&sample("images/photo.jpg"));
    assert!(val(&f, "Make").contains("CPE"));
    assert!(val(&f, "Model").contains("Fixture Cam"));
    assert!(val(&f, "Artist").contains("CPE Test Suite"));
    assert!(val(&f, "Copyright").contains("CC0"));
    assert!(val(&f, "ImageDescription").contains("Baseline EXIF sample"));
    // Camera intrinsics are read-only; descriptive tags are editable.
    assert!(!f.iter().find(|x| x.key == "Make").unwrap().editable);
    assert!(f.iter().find(|x| x.key == "Artist").unwrap().editable);
    assert!(f.iter().all(|x| x.group == "exif"));
}

#[test]
fn pdf_info_baseline() {
    let f = read_pdf(&sample("documents/doc.pdf"));
    assert_eq!(val(&f, "Title"), "Baseline Sample");
    assert_eq!(val(&f, "Author"), "CPE Test Suite");
    assert_eq!(val(&f, "Subject"), "Baseline fixture");
    assert_eq!(val(&f, "Keywords"), "cpe,sample,baseline");
    assert_eq!(val(&f, "Producer"), "gen_samples.py");
    assert_eq!(val(&f, "Date Created"), "D:20260725110000");
    assert!(f.iter().all(|x| x.group == "pdf"));
    // Descriptive tags are editable (CPE-1301 write codec); producer intrinsics stay read-only.
    assert!(f.iter().find(|x| x.key == "Title").unwrap().editable);
    assert!(!f.iter().find(|x| x.key == "Producer").unwrap().editable);
}

#[test]
fn mp4_video_baseline() {
    let f = read_mp4(&sample("video/clip.mp4"));
    assert_eq!(val(&f, "Title"), "Baseline Sample");
    assert_eq!(val(&f, "Artist"), "CPE Test Suite");
    assert_eq!(val(&f, "Album"), "Known Fixtures");
    assert_eq!(val(&f, "Year"), "2026");
    assert!(f.iter().all(|x| x.group == "video"));
}

#[test]
fn text_samples_exist_and_are_readable() {
    for rel in ["text/notes.txt", "text/readme.md", "text/data.json", "text/table.csv", "text/hello.py"] {
        let bytes = sample(rel);
        assert!(!bytes.is_empty(), "{rel} is empty");
        assert!(std::str::from_utf8(&bytes).is_ok(), "{rel} is not valid UTF-8");
    }
    // The PNG is a real image: PNG signature.
    assert_eq!(&sample("images/pixel.png")[..8], b"\x89PNG\r\n\x1a\n");
}
