//! Baseline assertions over the pristine `samples/` fixtures (CPE-1042).
//!
//! `samples/` holds small, synthetic, KNOWN-metadata files (generated by `scripts/gen_samples.py`). This
//! test reads each one through the shipped read codecs and asserts the documented baseline — so the
//! fixtures double as a regression guard: if a codec or a sample drifts, this fails. Keep it in sync with
//! `samples/README.md`.

use cpe_server::media_meta_edit::MetaField;
use cpe_server::media_meta_read::{read_exif, read_flac, read_id3v2, read_ogg, read_pdf};
use cpe_server::video_meta_read::read_mp4;
use std::fs;
use std::path::PathBuf;

fn sample_path(rel: &str) -> String {
    let p: PathBuf = [env!("CARGO_MANIFEST_DIR"), "..", "..", "samples", rel].iter().collect();
    p.to_string_lossy().to_string()
}

fn sample(rel: &str) -> Vec<u8> {
    fs::read(sample_path(rel)).unwrap_or_else(|e| panic!("read sample {rel}: {e}"))
}

fn val<'a>(fields: &'a [MetaField], key: &str) -> &'a str {
    fields
        .iter()
        .find(|f| f.key == key)
        .unwrap_or_else(|| panic!("missing field {key:?} (have: {:?})", fields.iter().map(|f| &f.key).collect::<Vec<_>>()))
        .value
        .as_str()
}

#[test]
fn mp3_id3_baseline() {
    let f = read_id3v2(&sample("audio/track.mp3"));
    assert_eq!(val(&f, "Title"), "Baseline Sample");
    assert_eq!(val(&f, "Artist"), "CPE Test Suite");
    assert_eq!(val(&f, "Album"), "Known Fixtures");
    assert_eq!(val(&f, "Year"), "2026");
    assert_eq!(val(&f, "Track"), "3/10");
    assert_eq!(val(&f, "Genre"), "Ambient");
    assert!(val(&f, "Comment").starts_with("Pristine CPE sample"));
    assert!(f.iter().all(|x| x.group == "id3" && x.editable));
}

fn assert_vorbis_baseline(f: &[MetaField]) {
    assert_eq!(val(f, "Title"), "Baseline Sample");
    assert_eq!(val(f, "Artist"), "CPE Test Suite");
    assert_eq!(val(f, "Album"), "Known Fixtures");
    assert_eq!(val(f, "Year"), "2026");
    assert_eq!(val(f, "Track"), "3");
    assert_eq!(val(f, "Genre"), "Ambient");
    assert!(f.iter().all(|x| x.group == "vorbis" && x.editable));
}

#[test]
fn flac_vorbis_baseline() {
    assert_vorbis_baseline(&read_flac(&sample("audio/track.flac")));
}

#[test]
fn ogg_vorbis_baseline() {
    assert_vorbis_baseline(&read_ogg(&sample("audio/track.ogg")));
}

#[test]
fn jpeg_exif_baseline() {
    // kamadak-exif renders ASCII values with surrounding quotes, so assert on the contained text.
    let f = read_exif(&sample("images/photo.jpg"));
    assert!(val(&f, "Make").contains("CPE"));
    assert!(val(&f, "Model").contains("Fixture Cam"));
    assert!(val(&f, "Artist").contains("CPE Test Suite"));
    assert!(val(&f, "Copyright").contains("CC0"));
    assert!(val(&f, "ImageDescription").contains("Baseline EXIF sample"));
    // Camera intrinsics are read-only; descriptive tags are editable.
    assert!(!f.iter().find(|x| x.key == "Make").unwrap().editable);
    assert!(f.iter().find(|x| x.key == "Artist").unwrap().editable);
    assert!(f.iter().all(|x| x.group == "exif"));
}

#[test]
fn pdf_info_baseline() {
    // `documents/doc.pdf` is a real, valid, byte-accurate-xref 3-page PDF generated by
    // `scripts/gen_samples.py::make_pdf()` (CPE-1357/1358) — the OLD fixture it replaced was a 406-byte
    // structurally-invalid file (`/Kids [] /Count 0`, no xref) that crashed the PDF preview; those exact
    // bytes are preserved as the CPE-1357 regression fixture `documents/malformed.pdf` (see
    // `gui-smoke/specs/samples.smoke.ts` and `samples/README.md`'s "PDF fixtures" section). `doc.pdf`
    // carries the SAME full `/Info` baseline every other sample format asserts (compare
    // `mp3_id3_baseline`/`mp4_video_baseline` above) — a brief intermediate commit swapped in a
    // Pillow-rendered raster PDF with a slimmer `/Info` dict (Title only, no Author/Subject/Keywords/
    // Producer); this generator-produced fixture restores the full baseline and stays deterministic/
    // reproducible via `python scripts/gen_samples.py`.
    let f = read_pdf(&sample("documents/doc.pdf"));
    assert_eq!(val(&f, "Title"), "Baseline Sample");
    assert_eq!(val(&f, "Author"), "CPE Test Suite");
    assert_eq!(val(&f, "Subject"), "Baseline fixture");
    assert_eq!(val(&f, "Keywords"), "cpe,sample,baseline");
    assert_eq!(val(&f, "Creator"), "gen_samples.py");
    assert_eq!(val(&f, "Producer"), "gen_samples.py");
    assert_eq!(val(&f, "Date Created"), "D:20260725110000");
    assert_eq!(val(&f, "Date Modified"), "D:20260725110000");
    assert!(f.iter().all(|x| x.group == "pdf"));
    // Descriptive tags are editable (CPE-1301 write codec); producer intrinsics stay read-only.
    for key in ["Title", "Author", "Subject", "Keywords"] {
        assert!(f.iter().find(|x| x.key == key).unwrap().editable, "{key} should be editable");
    }
    for key in ["Creator", "Producer", "Date Created", "Date Modified"] {
        assert!(!f.iter().find(|x| x.key == key).unwrap().editable, "{key} should be read-only");
    }
}

#[test]
fn mp4_video_baseline() {
    let f = read_mp4(&sample("video/clip.mp4"));
    assert_eq!(val(&f, "Title"), "Baseline Sample");
    assert_eq!(val(&f, "Artist"), "CPE Test Suite");
    assert_eq!(val(&f, "Album"), "Known Fixtures");
    assert_eq!(val(&f, "Year"), "2026");
    assert!(f.iter().all(|x| x.group == "video"));
}

#[test]
fn text_samples_exist_and_are_readable() {
    for rel in ["text/notes.txt", "text/readme.md", "text/data.json", "text/table.csv", "text/hello.py"] {
        let bytes = sample(rel);
        assert!(!bytes.is_empty(), "{rel} is empty");
        assert!(std::str::from_utf8(&bytes).is_ok(), "{rel} is not valid UTF-8");
    }
    // The PNG is a real image: PNG signature.
    assert_eq!(&sample("images/pixel.png")[..8], b"\x89PNG\r\n\x1a\n");
}

// ─────────────────────────────────────────────────────────────────────────────────────────────────────
// Substantial-fixture assertions (CPE-1361): each new REAL fixture opens through its shipped parser.
// ─────────────────────────────────────────────────────────────────────────────────────────────────────

/// The multi-folder ZIP lists its real tree and an inner file's bytes extract intact (the CPE-1360
/// archive-inner-preview path).
#[test]
fn zip_lists_real_tree_and_extracts_inner_file() {
    use cpe_server::archive::{extract_archive_entry_any, read_archive_entries};
    let path = sample_path("archives/sample.zip");
    let entries = read_archive_entries(&path).expect("list zip");
    let names: Vec<&str> = entries.iter().map(|e| e.name.as_str()).collect();
    for expected in ["docs/readme.md", "docs/sub/notes.txt", "images/logo.png", "data/table.csv", "src/main.py"] {
        assert!(names.iter().any(|n| n == &expected), "zip missing {expected}; have {names:?}");
    }
    assert!(entries.iter().any(|e| e.is_dir), "zip should carry explicit directory entries");

    let extracted = extract_archive_entry_any(&path, "docs/readme.md").expect("extract inner file");
    let text = fs::read_to_string(&extracted).expect("read extracted");
    assert!(text.contains("Sample Archive"), "inner readme content extracted: {text:?}");
}

/// The hand-built RAR4 lists the same tree via the pure-Rust `rar_entries` walker (CPE-1347).
#[test]
fn rar_lists_real_tree() {
    use cpe_server::rar::rar_entries;
    let entries = rar_entries(&sample_path("archives/sample.rar")).expect("list rar");
    let files: Vec<&str> = entries.iter().filter(|e| !e.is_dir).map(|e| e.name.as_str()).collect();
    for expected in ["docs/readme.md", "docs/sub/notes.txt", "images/logo.png", "data/table.csv", "src/main.py"] {
        assert!(files.iter().any(|n| n == &expected), "rar missing file {expected}; have {files:?}");
    }
    assert!(entries.iter().any(|e| e.is_dir && e.name == "images"), "rar should list directory entries");
    let readme = entries.iter().find(|e| e.name == "docs/readme.md").unwrap();
    assert!(readme.size > 0, "stored file advertises its real (uncompressed) size");
}

/// The SQLite database opens read-only and reports its several tables + real row counts (data-grid preview).
#[test]
fn sqlite_reports_tables_and_row_counts() {
    use cpe_server::data_preview::sqlite_info;
    let info = sqlite_info(&sample_path("database/mini.sqlite")).expect("read sqlite");
    assert!(info.contains("users (table) — 20 rows"), "users table + rows: {info}");
    assert!(info.contains("products (table) — 12 rows"), "products table + rows: {info}");
    assert!(info.contains("orders (table) — 40 rows"), "orders table + rows: {info}");
    assert!(info.contains("order_summary (view)"), "view present: {info}");
    assert!(info.contains("columns: id, name, email"), "column list present: {info}");
}

/// The WASM module disassembles to meaningful WAT exporting `add` and `fib` (binary-info preview).
#[test]
fn wasm_disassembles_to_add_and_fib() {
    use cpe_server::binary_preview::wasm_info;
    let wat = wasm_info(&sample_path("other/tiny.wasm"), 64 * 1024).expect("disassemble wasm");
    assert!(wat.contains("func"), "WAT has functions: {wat}");
    assert!(wat.contains("add"), "exports add: {wat}");
    assert!(wat.contains("fib"), "exports fib: {wat}");
}

/// The TTF renders a real "Aa" specimen (non-empty ink) through the glyph-sheet thumbnailer.
#[test]
fn ttf_renders_a_specimen_with_ink() {
    use cpe_server::thumb_font::render_glyph_sheet;
    let img = render_glyph_sheet(&sample("fonts/mini.ttf"), "ttf", 64).expect("render glyph sheet");
    let rgba = img.to_rgba8();
    let has_ink = rgba.pixels().any(|p| p.0[0] < 250 || p.0[1] < 250 || p.0[2] < 250);
    assert!(has_ink, "the full-ASCII font must paint real glyph ink for the 'Aa' specimen");
}

/// The TIFF decodes and transcodes to a PNG data URL (decoded-image preview path).
#[test]
fn tiff_transcodes_to_png_data_url() {
    use cpe_server::image_preview::read_image_data_url;
    let url = read_image_data_url(&sample_path("images/photo.tiff")).expect("transcode tiff");
    assert!(url.starts_with("data:image/png;base64,"), "decoded-image preview yields a PNG data URL");
}
