//! Sidecar scaffolder (CPE-303).
//!
//! Generates a new, contract-compliant sidecar skeleton so a Mega-Feature starts
//! correct on day one — the thing that makes this a *platform*, not a one-off. The
//! generation is a pure function ([`scaffold`]) returning `(relative path, content)`
//! pairs, so it is fully unit-testable; the `create_sidecar` binary is a thin CLI that
//! writes those files to disk.

/// A generated file: path relative to the new crate's root, and its content.
pub type GeneratedFile = (String, String);

/// A valid crate/sidecar name: lowercase letters, digits, and single hyphens; must
/// start with a letter. (Mirrors Cargo's package-name rules closely enough.)
pub fn is_valid_name(name: &str) -> bool {
    let mut chars = name.chars();
    let first_ok = matches!(chars.next(), Some(c) if c.is_ascii_lowercase());
    first_ok
        && name.len() >= 2
        && !name.contains("--")
        && !name.ends_with('-')
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
}

/// Generate the files for a new sidecar named `name`. Returns an error if the name is
/// invalid. The result is transport-ready: it handshakes, requests one capability,
/// reaches Ready, and echoes requests — a compliant starting point to build on.
pub fn scaffold(name: &str) -> Result<Vec<GeneratedFile>, String> {
    if !is_valid_name(name) {
        return Err(format!(
            "invalid sidecar name '{name}': use lowercase letters, digits and single \
             hyphens, starting with a letter"
        ));
    }
    // A snake identifier for the sidecar id shown in the manifest/Hello.
    let id = name.to_string();

    let cargo_toml = format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
description = "A Cross-Platform Explorer sidecar."

# A sidecar depends ONLY on the contract — never on the host or the explorer
# (ADR 0001). Adjust the path if this crate is moved.
[dependencies]
sidecar-contract = {{ path = "../contract" }}
serde_json = "1"
"#
    );

    let main_rs = format!(
        r#"//! `{name}` sidecar — generated by create-sidecar (CPE-303).
//!
//! Protocol: emit `Hello`; on `Welcome` emit `Lifecycle::Ready`; answer `Request`s;
//! exit on `sidecar.shutdown`. Use only capabilities that arrive GRANTED in the
//! `Welcome`. Build your feature by adding request handlers and (if granted) sending
//! capability requests such as `context.current`, `storage.dir`, `secrets.get`.

use std::io::{{BufRead, Write}};

use sidecar_contract::{{
    Capability, Envelope, Hello, Lifecycle, Message, Response, CONTRACT_VERSION,
}};

fn emit(out: &mut impl Write, env: &Envelope) {{
    let _ = writeln!(out, "{{}}", env.to_json().expect("serialize"));
    let _ = out.flush();
}}

fn main() {{
    let stdin = std::io::stdin();
    let mut stdout = std::io::stdout();

    emit(
        &mut stdout,
        &Envelope::new(
            0,
            Message::Hello(Hello {{
                sidecar_id: "{id}".into(),
                sidecar_version: env!("CARGO_PKG_VERSION").into(),
                contract_version: CONTRACT_VERSION,
                capabilities_requested: vec![Capability::Context],
                auth_token: std::env::var(sidecar_contract::AUTH_TOKEN_ENV).ok(),
            }}),
        ),
    );

    for line in stdin.lock().lines() {{
        let line = match line {{ Ok(l) => l, Err(_) => break }};
        if line.trim().is_empty() {{ continue; }}
        let env = match Envelope::from_json(line.trim()) {{ Ok(e) => e, Err(_) => continue }};
        match env.message {{
            Message::Welcome(_welcome) => {{
                // TODO: read _welcome.capabilities_granted and start your work.
                emit(&mut stdout, &Envelope::new(0, Message::Lifecycle(Lifecycle::Ready)));
            }}
            Message::Request(req) => {{
                if req.method == "sidecar.shutdown" {{ std::process::exit(0); }}
                // TODO: handle your own methods here.
                let reply = Response {{ result: Ok(serde_json::json!({{ "ok": true }})) }};
                emit(&mut stdout, &Envelope::new(env.id, Message::Response(reply)));
            }}
            _ => {{}}
        }}
    }}
}}
"#
    );

    let manifest = format!(
        r#"{{
  "schema_version": 1,
  "id": "{id}",
  "name": "{name}",
  "version": "0.1.0",
  "contract_version": {{ "major": {major}, "minor": {minor} }},
  "entry": {{
    "windows": {{ "command": "{name}.exe" }},
    "macos":   {{ "command": "{name}" }},
    "linux":   {{ "command": "{name}" }}
  }},
  "capabilities": ["context"],
  "ui": null
}}
"#,
        major = sidecar_contract::CONTRACT_VERSION.major,
        minor = sidecar_contract::CONTRACT_VERSION.minor,
    );

    let readme = format!(
        "# {name}\n\nA Cross-Platform Explorer sidecar (see `docs/adr/0001-sidecar-platform.md`).\n\n\
         - `src/main.rs` — the sidecar process. Depends only on `sidecar-contract`.\n\
         - `sidecar.json` — the manifest the host's registry loads.\n\n\
         Validate it with the conformance kit and grow it from the template TODOs.\n"
    );

    Ok(vec![
        ("Cargo.toml".into(), cargo_toml),
        ("src/main.rs".into(), main_rs),
        ("sidecar.json".into(), manifest),
        ("README.md".into(), readme),
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn valid_and_invalid_names() {
        assert!(is_valid_name("ai-console"));
        assert!(is_valid_name("agent2"));
        assert!(!is_valid_name("AI")); // uppercase
        assert!(!is_valid_name("1abc")); // starts with digit
        assert!(!is_valid_name("a--b")); // double hyphen
        assert!(!is_valid_name("trailing-")); // trailing hyphen
        assert!(!is_valid_name("x")); // too short
        assert!(!is_valid_name("has space"));
    }

    #[test]
    fn scaffold_rejects_bad_names() {
        assert!(scaffold("Bad Name").is_err());
    }

    #[test]
    fn scaffold_emits_the_expected_files() {
        let files = scaffold("my-feature").unwrap();
        let paths: Vec<&str> = files.iter().map(|(p, _)| p.as_str()).collect();
        assert!(paths.contains(&"Cargo.toml"));
        assert!(paths.contains(&"src/main.rs"));
        assert!(paths.contains(&"sidecar.json"));
        assert!(paths.contains(&"README.md"));
    }

    #[test]
    fn generated_content_wires_the_name_and_contract() {
        let files = scaffold("my-feature").unwrap();
        let get = |p: &str| files.iter().find(|(x, _)| x == p).unwrap().1.clone();

        let cargo = get("Cargo.toml");
        assert!(cargo.contains("name = \"my-feature\""));
        assert!(cargo.contains("sidecar-contract"));

        let main = get("src/main.rs");
        assert!(main.contains("sidecar_id: \"my-feature\""));
        assert!(main.contains("CONTRACT_VERSION"));
        assert!(main.contains("Lifecycle::Ready"));

        let manifest = get("sidecar.json");
        assert!(manifest.contains("\"id\": \"my-feature\""));
        assert!(manifest.contains("\"schema_version\": 1"));
        // The manifest's contract major matches what this build speaks.
        assert!(manifest.contains(&format!(
            "\"major\": {}",
            sidecar_contract::CONTRACT_VERSION.major
        )));
    }

    #[test]
    fn generated_manifest_is_valid_json() {
        let files = scaffold("valid-json").unwrap();
        let manifest = &files.iter().find(|(p, _)| p == "sidecar.json").unwrap().1;
        let parsed: serde_json::Value = serde_json::from_str(manifest).unwrap();
        assert_eq!(parsed["id"], "valid-json");
    }
}
